AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create a public website-enabled S3 bucket.

Parameters:

  S3bucketName:
    Description: Postfix name for created resources
    Type: String

  DeployName:
    Description: Prefix name for created resources
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Ref: S3bucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 
        Ref: S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: S3Bucket
                  - "/*"
Outputs:
  S3BucketDomainName:
    Value: 
      Fn::GetAtt: [S3Bucket, DomainName]
    Export:
      Name:
        Fn::Join:
          - "-"
          - - Ref: DeployName
            - S3bucketName
            - DomainName

  S3BucketWebsiteURL:
    Value: 
      Fn::GetAtt: [S3Bucket, WebsiteURL]
    Export:
      Name:
        Fn::Join:
          - "-"
          - - Ref: DeployName
            - S3Bucket
            - URL
