openapi: "3.0.1"
info:
  title: "WellArchitectedSelectorHttpApi"
  version: "2025-03-09 16:38:12UTC"
servers:
- url: "https://forr4650b8.execute-api.us-east-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
tags:
- name: "aws:cloudformation:stack-id"
  x-amazon-apigateway-tag-value: "arn:aws:cloudformation:us-east-2:788715698479:stack/WellArchitected-Selector-APIStack-1XDTCM4L2LPNN/0ee8acc0-fc44-11ef-b469-02846cd5b029"
- name: "aws:cloudformation:stack-name"
  x-amazon-apigateway-tag-value: "WellArchitected-Selector-APIStack-1XDTCM4L2LPNN"
- name: "aws:cloudformation:logical-id"
  x-amazon-apigateway-tag-value: "HttpApi"
paths:
  /verifyToken:
    get:
      responses:
        default:
          description: "Default response for GET /verifyToken"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:788715698479:function:WellArchitected-Selector-verifyToken/invocations"
        connectionType: "INTERNET"
    post:
      responses:
        default:
          description: "Default response for POST /verifyToken"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:788715698479:function:WellArchitected-Selector-verifyToken/invocations"
        connectionType: "INTERNET"
x-amazon-apigateway-importexport-version: "1.0"
