AWSTemplateFormatVersion: "2010-09-09"

Conditions:
  HasRoute53Domain:
    Fn::Not:
      - Fn::Equals:
          - Ref: HOSTEDZONEID
          - ""

Parameters:
  DEPLOYNAME:
    Type: String
    Description: Prefix for resources
    Default: ""

  HOSTEDZONEID:
    Type: String
    Description: Route 53 Hosted Zone ID. Leave blank if no Route 53 domain is available.
    Default: ""

  DOMAINNAME:
    Type: String
    Description: Custom domain name for CloudFront. Leave blank if not using a custom domain.
    Default: ""

  CERTARN:
    Type: String
    Default: ""
  ApiEndpoint:
    Type: String
  S3BucketDomainName:
    Type: String

Resources:
  ForwardAllCookiesPolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: ForwardAllCookiesPolicy
        Comment: Policy to forward all cookies to origin
        DefaultTTL: 0 # Example TTL
        MaxTTL: 0 # Example TTL
        MinTTL: 0 # Example TTL
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          CookiesConfig:
            CookieBehavior: all # This forwards all cookies
          HeadersConfig:
            HeaderBehavior: none # Or whitelist specific headers
          QueryStringsConfig:
            QueryStringBehavior: none # Or whitelist specific query strings
                
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !Ref S3BucketDomainName
            S3OriginConfig: {}
          - Id: ApiOrigin
            DomainName:
              Fn::Select:
                - 1
                - Fn::Split:
                    - "://"
                    - !Ref ApiEndpoint
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
  
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
            
        CacheBehaviors:
          - PathPattern: /v1/*
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: !Ref ForwardAllCookiesPolicy


        ViewerCertificate:
          Fn::If:
            - HasRoute53Domain
            - 
              AcmCertificateArn: !Ref CERTARN
              SslSupportMethod: sni-only
              MinimumProtocolVersion: TLSv1.2_2019
            -
              CloudFrontDefaultCertificate: true
  
        Aliases:
          Fn::If:
            - HasRoute53Domain
            - - !Ref DOMAINNAME
            - !Ref AWS::NoValue

  Route53RecordSet:
    Condition: HasRoute53Domain
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Ref: HOSTEDZONEID
      Name: 
        Ref: DOMAINNAME
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: 
          Fn::GetAtt: 
            - CloudFrontDistribution
            - DomainName

Outputs:
  CloudFrontURL:
    Description: URL of the CloudFront distribution
    Export:
      Name:
        Fn::Join:
          - "-"
          - - Ref: DEPLOYNAME
            - CloudFront
            - URL
    Value:
      Fn::Join:
        - ""
        - - "https://"
          - Fn::GetAtt:
              - CloudFrontDistribution
              - DomainName
