AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to deploy a Python Lambda function with API Gateway v2 and DynamoDB."

Parameters:
  DEPLOY_NAME:
    Description: "Prefix name for created resources"
    Type: String
  S3BUCKET:
    Description: "S3 bucket name containing Lambda function code"
    Type: String

Resources:
  TableSquads:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:  !Sub "${DEPLOY_NAME}-squads"
      AttributeDefinitions:
        - AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

  TableHackers:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:  !Sub "${DEPLOY_NAME}-hackers"
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

  TableMachines:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:  !Sub "${DEPLOY_NAME}-machines"
      AttributeDefinitions:
        - AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

  TableServices:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:  !Sub "${DEPLOY_NAME}-services"
      AttributeDefinitions:
        - AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

  TableServiceChecks:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:  !Sub "${DEPLOY_NAME}-serviceChecks"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  TableInstances:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:  !Sub "${DEPLOY_NAME}-instances"
      AttributeDefinitions:
        - AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

  TableEvent:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:  !Sub "${DEPLOY_NAME}-event"
      AttributeDefinitions:
        - AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

