AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to deploy a Python Lambda function with API Gateway v2 and DynamoDB."

Parameters:
  DEPLOYNAME:
    Description: "Prefix name for created resources"
    Type: String

Resources:
  SSMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${DEPLOYNAME}-SSMRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "${DEPLOYNAME}-SSMInstanceProfile"
      Roles:
        - !Ref SSMRole
        
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${DEPLOYNAME}LambdaExecution"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"            
              - Effect: Allow
                Action:
                  - lambda:*
                Resource: "arn:aws:lambda:*:*:*"
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "arn:aws:dynamodb:*:*:*"
              - Effect: Allow
                Action:
                  - events:*
                Resource: "arn:aws:events:*:*:*" 
              - Effect: Allow
                Action:
                  - ec2:*
                Resource: "*"
                     
  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${DEPLOYNAME}-LambdaIntegrationRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${DEPLOYNAME}-ApiGatewayLambdaPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - lambda:GetFunction
                  - lambda:GetFunctionConfiguration
                  - lambda:ListFunctions
                Resource: "arn:aws:lambda:*:*:function:*"

  EventsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${DEPLOYNAME}-eventsExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole

Outputs:
  LambdaExecutionRoleArn:
    Description: "ARN of role needed by lambda functions"
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: LambdaExecutionRoleArn
  EventsExecutionRoleArn:
    Description: "ARN of role needed to invoke lambda functions"
    Value: !GetAtt EventsExecutionRole.Arn
    Export:
      Name: EventsExecutionRoleArn
  ApiGatewayRoleArn:
    Description: "ARN of role needed to invoke lambda functions"
    Value: !GetAtt ApiGatewayRole.Arn
    Export:
      Name: ApiGatewayRoleArn
