AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack that creates nested stacks

Parameters:
  S3BUCKET:
    Description: Globally unique name for our bucket
    Type: String
  DEPLOYNAME:
    Description: Prefix name for created resources
    Type: String
  DOMAINNAME:
    Type: String
  CERTARN:
    Type: String 
  HOSTEDZONEID:
    Type: String
    
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
          Fn::Join:
                  - ""
                  - - "https://"
                    - Ref: DEPLOYNAME
                    - ".s3."
                    - !Ref AWS::Region
                    - ".amazonaws.com/deploy/"
                    - "vpc.yaml"
      Parameters:
        DEPLOYNAME: !Ref DEPLOYNAME
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
          Fn::Join:
                  - ""
                  - - "https://"
                    - Ref: DEPLOYNAME
                    - ".s3."
                    - !Ref AWS::Region
                    - ".amazonaws.com/deploy/"
                    - "iam.yaml"
      Parameters:
        DEPLOYNAME: !Ref DEPLOYNAME

  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
          Fn::Join:
                  - ""
                  - - "https://"
                    - Ref: DEPLOYNAME
                    - ".s3."
                    - !Ref AWS::Region
                    - ".amazonaws.com/deploy/"
                    - "db.yaml"
      Parameters:
        DEPLOYNAME: !Ref DEPLOYNAME

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
          Fn::Join:
                  - ""
                  - - "https://"
                    - Ref: DEPLOYNAME
                    - ".s3."
                    - !Ref AWS::Region
                    - ".amazonaws.com/deploy/"
                    - "lambda.yaml"
      Parameters:
        DEPLOYNAME: !Ref DEPLOYNAME
        S3BUCKET: !Ref DEPLOYNAME

  APIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
          Fn::Join:
                  - ""
                  - - "https://"
                    - Ref: DEPLOYNAME
                    - ".s3."
                    - !Ref AWS::Region
                    - ".amazonaws.com/deploy/"
                    - "api.yaml"
      Parameters:
        DEPLOYNAME: !Ref DEPLOYNAME
        S3BUCKET: !Ref DEPLOYNAME

#  CDNStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL:
#          Fn::Join:
#                  - ""
#                  - - "https://"
#                    - Ref: DEPLOYNAME
#                    - ".s3."
#                    - !Ref AWS::Region
#                    - ".amazonaws.com/deploy/"
#                    - "cdn.yaml"
#      Parameters:
#        CERTARN: !Ref CERTARN
#        DEPLOYNAME: !Ref DEPLOYNAME
#        HOSTEDZONEID: !Ref HOSTEDZONEID
#        API: !GetAtt "APIStack.Outputs.ApiEndPoint"

Outputs:
  VpcId:
    Value: !GetAtt VPCStack.Outputs.VpcId
    Description: "VPC ID from the VPC stack"

  LambdaFunctionArn:
    Value: !GetAtt LambdaStack.Outputs.LambdaFunctionArn
    Description: "Lambda Function ARN from the Lambda stack"
