AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack that creates nested stacks

Parameters:
  S3BUCKET:
    Description: Globally unique name for our bucket
    Type: String
  DEPLOYNAME:
    Description: Prefix name for created resources
    Type: String
  DOMAINNAME:
    Type: String
    
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://nadialin.s3.us-east-2.amazonaws.com/deploy/vpc.yaml"
      Parameters:
        VpcCIDR: "10.0.0.0/16"
        DEPLOYNAME: ${DEPLOYNAME}

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DEPLOYNAME}.s3.us-east-2.amazon.com/deploy/iam.yaml"

  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DEPLOYNAME}.s3.us-east-2.amazon.com/deploy/db.yaml"

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DEPLOYNAME}.s3.us-east-2.amazon.com/deploy/lambda.yaml"
      Parameters:
        LambdaRoleArn: !GetAtt IAMStack.Outputs.LambdaExecutionRoleArn
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        SubnetIds: !GetAtt VPCStack.Outputs.SubnetIds

  APIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DEPLOYNAME}.s3.us-east-2.amazon.com/deploy/api.yaml"

  CDNStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DEPLOYNAME}.s3.us-east-2.amazon.com/deploy/cdn.yaml"

Outputs:
  VpcId:
    Value: !GetAtt VPCStack.Outputs.VpcId
    Description: "VPC ID from the VPC stack"

  LambdaFunctionArn:
    Value: !GetAtt LambdaStack.Outputs.LambdaFunctionArn
    Description: "Lambda Function ARN from the Lambda stack"
