AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack that creates nested stacks

Parameters:
  S3BUCKET:
    Description: Globally unique name for our bucket
    Type: String
  DEPLOYNAME:
    Description: Prefix name for created resources
    Type: String
  DOMAINNAME:
    Type: String
    
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
          Fn::Join:
                  - ""
                  - - "https://"
                    - Ref: DEPLOYNAME
                    - ".s3."
                    - !Ref AWS::Region
                    - ".amazonaws.com/deploy/"
                    - "vpc.yaml"
      Parameters:
        DEPLOYNAME: !Sub "{DEPLOYNAME}"

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
          Fn::Join:
                  - ""
                  - - "https://"
                    - Ref: DEPLOYNAME
                    - ".s3."
                    - !Ref AWS::Region
                    - ".amazonaws.com/deploy/"
                    - "iam.yaml"
      Parameters:
        DEPLOYNAME: !Sub "{DEPLOYNAME}"

  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
          Fn::Join:
                  - ""
                  - - "https://"
                    - Ref: DEPLOYNAME
                    - ".s3."
                    - !Ref AWS::Region
                    - ".amazonaws.com/deploy/"
                    - "db.yaml"
      Parameters:
        DEPLOYNAME: !Sub "{DEPLOYNAME}"

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
          Fn::Join:
                  - ""
                  - - "https://"
                    - Ref: DEPLOYNAME
                    - ".s3."
                    - !Ref AWS::Region
                    - ".amazonaws.com/deploy/"
                    - "lambda.yaml"
      Parameters:
        ROLEARN: !GetAtt IAMStack.Outputs.LambdaExecutionRoleArn
        DEPLOYNAME: !Sub "{DEPLOYNAME}"
        S3BUCKET: !Sub "{DEPLOYNAME}"

  APIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
          Fn::Join:
                  - ""
                  - - "https://"
                    - Ref: DEPLOYNAME
                    - ".s3."
                    - !Ref AWS::Region
                    - ".amazonaws.com/deploy/"
                    - "api.yaml"
      Parameters:
        ROLEARN: !GetAtt IAMStack.Outputs.LambdaExecutionRoleArn
        DEPLOYNAME: !Sub "{DEPLOYNAME}"
        S3BUCKET: !Sub "{DEPLOYNAME}"

  CDNStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
          Fn::Join:
                  - ""
                  - - "https://"
                    - Ref: DEPLOYNAME
                    - ".s3."
                    - !Ref AWS::Region
                    - ".amazonaws.com/deploy/"
                    - "cdn.yaml"
      Parameters:
        CERTARN: !Sub "{CERTARN}"
        DEPLOYNAME: !Sub "{DEPLOYNAME}"
        HOSTEDZONEID: !Sub "{HOSTEDZONEID}"
        API: !GetAtt !Sub "APIStack.Outputs.${DEPLOYNAME}-ApiEndPoint"

Outputs:
  VpcId:
    Value: !GetAtt VPCStack.Outputs.VpcId
    Description: "VPC ID from the VPC stack"

  LambdaFunctionArn:
    Value: !GetAtt LambdaStack.Outputs.LambdaFunctionArn
    Description: "Lambda Function ARN from the Lambda stack"
