AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack that creates nested stacks


Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/S3BUCKET/bucket/vpc.yaml"
      Parameters:
        VpcCIDR: "10.0.0.0/16"

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/S3BUCKET/bucket/iam.yaml"

  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/S3BUCKET/bucket/db.yaml"

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/S3BUCKET/bucket/lambda.yaml"
      Parameters:
        LambdaRoleArn: !GetAtt IAMStack.Outputs.LambdaExecutionRoleArn
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        SubnetIds: !GetAtt VPCStack.Outputs.SubnetIds

  APIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/S3BUCKET/bucket/api.yaml"

  CDNStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/S3BUCKET/bucket/cdn.yaml"


Outputs:
  VpcId:
    Value: !GetAtt VPCStack.Outputs.VpcId
    Description: "VPC ID from the VPC stack"

  LambdaFunctionArn:
    Value: !GetAtt LambdaStack.Outputs.LambdaFunctionArn
    Description: "Lambda Function ARN from the Lambda stack"
