AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack that creates nested stacks

Parameters:
  S3BUCKET:
    Description: Globally unique name for our bucket
    Type: String
  DEPLOYNAME:
    Description: Prefix name for created resources
    Type: String
  DOMAINNAME:
    Type: String
    
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
          Fn::Join:
                  - ""
                  - - "https://"
                    - Ref: DEPLOYNAME
                    - ".s3.us-east-2.amazonaws.com/deploy/vpc.yaml"
      Parameters:
        DEPLOYNAME: !Sub "{DEPLOYNAME}"

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://nadialin.s3.us-east-2.amazonaws.com/deploy/iam.yaml"
      Parameters:
        DEPLOYNAME: !Sub "{DEPLOYNAME}"

  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
          Fn::Join:
                  - ""
                  - - "https://nadialin.s3."
                    - !Ref AWS::Region
                    - ".amazonaws.com/deploy/db.yaml"
      Parameters:
        DEPLOYNAME: !Sub "{DEPLOYNAME}"

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DEPLOYNAME}.s3.us-east-2.amazonaws.com/deploy/lambda.yaml"
      Parameters:
        LambdaRoleArn: !GetAtt IAMStack.Outputs.LambdaExecutionRoleArn
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        SubnetIds: !GetAtt VPCStack.Outputs.SubnetIds
        DEPLOYNAME: !Sub "{DEPLOYNAME}"

  APIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DEPLOYNAME}.s3.{AWS:REGION}.amazonaws.com/deploy/api.yaml"
      Parameters:
        DEPLOYNAME: !Sub "{DEPLOYNAME}"

  CDNStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DEPLOYNAME}.s3.{AWS:REGION}.amazonaws.com/deploy/cdn.yaml"
      Parameters:
        DEPLOYNAME: !Sub "{DEPLOYNAME}"

Outputs:
  VpcId:
    Value: !GetAtt VPCStack.Outputs.VpcId
    Description: "VPC ID from the VPC stack"

  LambdaFunctionArn:
    Value: !GetAtt LambdaStack.Outputs.LambdaFunctionArn
    Description: "Lambda Function ARN from the Lambda stack"
