AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack that creates nested stacks

Resources:
  VPC_Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/S3BUCKET/vpc.yaml"
      Parameters:
        VpcCIDR: "10.0.0.0/16"

  IAM_Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/S3BUCKET/iam.yaml"

  DB_Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/S3BUCKET/db.yaml"

  Lambda_Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/S3BUCKET/lambda.yaml"
      Parameters:
        LambdaRoleArn: !GetAtt IAM_Stack.Outputs.LambdaExecutionRoleArn
        VpcId: !GetAtt VPC_Stack.Outputs.VpcId
        SubnetIds: !GetAtt VPC_Stack.Outputs.SubnetIds

  API_tack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/S3BUCKET/api.yaml"

  CDN_Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/S3BUCKET/cdn.yaml"


Outputs:
  VpcId:
    Value: !GetAtt VPC_Stack.Outputs.VpcId
    Description: "VPC ID from the VPC stack"

  LambdaFunctionArn:
    Value: !GetAtt Lambda_Stack.Outputs.LambdaFunctionArn
    Description: "Lambda Function ARN from the Lambda stack"
