AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack that creates nested stacks

Parameters:
  S3BUCKET:
    Description: Globally unique name for our bucket
    Type: String
  DEPLOYNAME:
    Description: Prefix name for created resources
    Type: String
  DOMAINNAME:
    Type: String
  CERTARN:
    Type: String 
  HOSTEDZONEID:
    Type: String
    
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DEPLOYNAME}.s3.${AWS::Region}.amazonaws.com/deploy/vpc.yaml"
      Parameters:
        DEPLOYNAME: !Ref DEPLOYNAME
        
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DEPLOYNAME}.s3.${AWS::Region}.amazonaws.com/deploy/iam.yaml"
      Parameters:
        DEPLOYNAME: !Ref DEPLOYNAME

  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DEPLOYNAME}.s3.${AWS::Region}.amazonaws.com/deploy/db.yaml"
      Parameters:
        DEPLOYNAME: !Ref DEPLOYNAME

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DEPLOYNAME}.s3.${AWS::Region}.amazonaws.com/deploy/lambda.yaml"
      Parameters:
        DEPLOYNAME: !Ref DEPLOYNAME
        S3BUCKET: !Ref DEPLOYNAME
        LambdaExecutionRoleArn: !GetAtt IAMStack.Outputs.LambdaExecutionRoleArn
        TableHackers: !GetAtt DBStack.Outputs.TableHackers

  APIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DEPLOYNAME}.s3.${AWS::Region}.amazonaws.com/deploy/api.yaml"
      Parameters:
        DEPLOYNAME: !Ref DEPLOYNAME
        S3BUCKET: !Ref DEPLOYNAME
        ApiGatewayRoleArn: !GetAtt IAMStack.Outputs.ApiGatewayRoleArn
        EventsExecutionRoleArn: !GetAtt IAMStack.Outputs.EventsExecutionRoleArn     

  CDNStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DEPLOYNAME}.s3.${AWS::Region}.amazonaws.com/deploy/cdn.yaml"
      Parameters:
        CERTARN: !Ref CERTARN
        DEPLOYNAME: !Ref DEPLOYNAME
        DOMAINNAME: !Ref DOMAINNAME
        HOSTEDZONEID: !Ref HOSTEDZONEID
        ApiEndpoint: !GetAtt APIStack.Outputs.ApiEndpoint
        S3BucketDomainName: !ImportValue S3BucketDomainName

Outputs:
  VpcId:
    Value: !GetAtt VPCStack.Outputs.VpcId
    Description: "VPC ID from the VPC stack"

