AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack that creates nested stacks

Parameters:
  DEPLOY_NAME:
    Type: String
  S3BUCKET:
    Type: String
    
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://nadialin.s3.amazonaws.com/deploy/vpc.yaml"
      Parameters:
        VpcCIDR: "10.0.0.0/16"

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        Fn::Join:
          - "-"
          - - "https://"
            - Ref: S3BUCKET
            - ".s3.amazonaws.com/deploy/iam.yaml"

  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        Fn::Join:
          - "-"
          - - "https://s3.amazonaws.com/"
            - Ref: S3BUCKET
            - "/db.yaml"

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        Fn::Join:
          - "-"
          - - "https://s3.amazonaws.com/"
            - Ref: S3BUCKET
            - "/lambda.yaml"
      Parameters:
        LambdaRoleArn: !GetAtt IAMStack.Outputs.LambdaExecutionRoleArn
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        SubnetIds: !GetAtt VPCStack.Outputs.SubnetIds

  APIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        Fn::Join:
          - "-"
          - - "https://s3.amazonaws.com/"
            - Ref: S3BUCKET
            - "/api.yaml"

  CDNStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        Fn::Join:
          - "-"
          - - "https://s3.amazonaws.com/"
            - Ref: S3BUCKET
            - "/cdn.yaml"

Outputs:
  VpcId:
    Value: !GetAtt VPCStack.Outputs.VpcId
    Description: "VPC ID from the VPC stack"

  LambdaFunctionArn:
    Value: !GetAtt LambdaStack.Outputs.LambdaFunctionArn
    Description: "Lambda Function ARN from the Lambda stack"
