AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create a dual-stack VPC with a single subnet and an Internet Gateway."

Parameters:
  DeployName:
    Description: "Prefix name for created resources"
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: "Name"
          Value: !Ref DeployName

  VPCAssociateIPv6CidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      VpcId: !Ref VPC
      AmazonProvidedIpv6CidrBlock: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: "Name"
          Value: !Sub "${DeployName}InternetGateway"

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: "Name"
          Value: !Sub "${DeployName}RouteTable"

  RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable

  IPv4DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway
    DependsOn: VPCGatewayAttachment

  IPv6DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationIpv6CidrBlock: "::/0"
      GatewayId: !Ref InternetGateway
    DependsOn: VPCGatewayAttachment

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.0.0/24"
      Ipv6CidrBlock: 
        Fn::Select:
          - "0"
          - Fn::GetAtt:
              - VPC
              - Ipv6CidrBlocks
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "Name"
          Value: !Sub "${DeployName}DualStackSubnet"
    DependsOn: VPCAssociateIPv6CidrBlock

Outputs:
  VpcId:
    Description: "VPC ID of the created VPC"
    Value: !Ref VPC

  SubnetId:
    Description: "Subnet ID of the created subnet"
    Value: !Ref Subnet

  InternetGatewayId:
    Description: "Internet Gateway ID"
    Value: !Ref InternetGateway
